#!/usr/bin/env bash
#
# NiceWatch agent installer
#
# Usage (run on the host you want to monitor, as root):
#   curl -fsSL https://<nicewatch-server>/install.sh | sudo bash -s -- \
#        --server https://<nicewatch-server> --token <BEARER_TOKEN> [--name web01]
#
# To keep the token out of `ps aux` / bash history, pass it via env instead:
#   NICEWATCH_TOKEN=xxx curl -fsSL https://<server>/install.sh \
#       | sudo -E bash -s -- --server https://<server> --name web01
#
# What it does (idempotent):
#   1. apt-get installs PHP CLI + composer if missing
#   2. downloads nicewatch-agent.zip from the central server
#   3. unpacks to /opt/nicewatch-agent
#   4. runs composer install --no-dev
#   5. writes /etc/nicewatch/agent.php with the supplied server URL + token
#   6. installs systemd .service + .timer and enables the timer (30 s cadence)
#
set -euo pipefail

SERVER="${NICEWATCH_SERVER:-}"
TOKEN="${NICEWATCH_TOKEN:-}"
HOSTNAME_ARG="${NICEWATCH_NAME:-}"
INSTALL_DIR="/opt/nicewatch-agent"
CONFIG_DIR="/etc/nicewatch"
SERVICE_USER="nicewatch"

# Prefer env vars over CLI args — keeps the bearer token out of `ps aux`,
# `/proc/$pid/cmdline`, audit logs and bash history. CLI flags remain as a
# convenience for the one-liner generated by the panel.
while [[ $# -gt 0 ]]; do
    case "$1" in
        --server)   SERVER="$2"; shift 2 ;;
        --token)    TOKEN="$2"; shift 2 ;;
        --name)     HOSTNAME_ARG="$2"; shift 2 ;;
        --dir)      INSTALL_DIR="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,16p' "$0"; exit 0 ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

# Strip the token from the script's own argv so a subsequent `ps` won't show it.
# (Best-effort; --token may still be in the shell process's argv until exit.)
unset NICEWATCH_TOKEN || true

if [[ -z "$SERVER" || -z "$TOKEN" ]]; then
    echo "Missing --server or --token. Run with --help for usage." >&2
    exit 1
fi

# Argument validation — refuse anything that could be a shell/PHP injection vector
# even though we generate the PHP config via var_export below (defense in depth).
if ! [[ "$TOKEN" =~ ^[A-Za-z0-9]{32,128}$ ]]; then
    echo "Invalid --token. Expected 32-128 alphanumeric characters (NiceWatch tokens are 64 chars)." >&2
    exit 1
fi
if ! [[ "$SERVER" =~ ^https?://[A-Za-z0-9.:/_-]+$ ]]; then
    echo "Invalid --server. Expected http(s)://host[:port][/path]." >&2
    exit 1
fi
if [[ -n "$HOSTNAME_ARG" ]] && ! [[ "$HOSTNAME_ARG" =~ ^[A-Za-z0-9._-]{1,253}$ ]]; then
    echo "Invalid --name. Expected DNS-safe characters only." >&2
    exit 1
fi
if [[ "${SERVER}" == http://* ]]; then
    echo "WARNING: --server uses plain HTTP. The bearer token will be sent in cleartext over the wire." >&2
    echo "         Switch the central server to HTTPS before relying on alerts in production." >&2
fi

if [[ $EUID -ne 0 ]]; then
    echo "Run as root (sudo)." >&2
    exit 1
fi

log() { printf '\033[36m[nicewatch]\033[0m %s\n' "$*"; }

# ---------- 1. Packages ----------
log "Installing PHP CLI + composer + unzip (if missing)…"
PHP_PKG=""
if ! command -v php >/dev/null 2>&1; then
    if   apt-cache show php8.3-cli >/dev/null 2>&1; then PHP_PKG="php8.3-cli php8.3-curl php8.3-mbstring php8.3-xml";
    elif apt-cache show php8.2-cli >/dev/null 2>&1; then PHP_PKG="php8.2-cli php8.2-curl php8.2-mbstring php8.2-xml";
    else PHP_PKG="php-cli php-curl php-mbstring php-xml"; fi
fi
DEBIAN_FRONTEND=noninteractive apt-get update -qq
# shellcheck disable=SC2086
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq $PHP_PKG composer unzip curl >/dev/null

# ---------- 2. Service user ----------
if ! id "$SERVICE_USER" >/dev/null 2>&1; then
    log "Creating service user '$SERVICE_USER'"
    useradd -r -s /usr/sbin/nologin "$SERVICE_USER"
fi

# ---------- 3. Download & verify & unpack ----------
ZIP_URL="${SERVER%/}/downloads/nicewatch-agent.zip"
TMP_ZIP=$(mktemp /tmp/nicewatch-agent.XXXX.zip)

log "Downloading $ZIP_URL"
if ! curl -fsSL -o "$TMP_ZIP" "$ZIP_URL"; then
    echo "Failed to download $ZIP_URL — is the NiceWatch server reachable?" >&2
    exit 1
fi

# Integrity check: compare against the SHA-256 the server published next to the ZIP.
# Catches corrupted transfers and version skew. (Note: when fetched over HTTPS this
# also detects tampering in transit; it does NOT defend against a fully compromised
# server — that trust is inherent to the curl|bash install model. Always use HTTPS.)
EXPECTED_SHA=$(curl -fsSL "${ZIP_URL}.sha256" 2>/dev/null | tr -d '[:space:]' || true)
if [[ -n "$EXPECTED_SHA" ]]; then
    ACTUAL_SHA=$(sha256sum "$TMP_ZIP" | awk '{print $1}')
    if [[ "$EXPECTED_SHA" != "$ACTUAL_SHA" ]]; then
        echo "Checksum mismatch for nicewatch-agent.zip!" >&2
        echo "  expected: $EXPECTED_SHA" >&2
        echo "  actual:   $ACTUAL_SHA" >&2
        echo "Aborting — the download is corrupted or tampered with." >&2
        rm -f "$TMP_ZIP"
        exit 1
    fi
    log "Checksum OK ($ACTUAL_SHA)"
else
    echo "WARNING: server did not publish a .sha256 — skipping integrity check." >&2
fi

log "Extracting to $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
# Unpack into a tmp dir then move so we don't half-overwrite a running install
TMP_EXTRACT=$(mktemp -d)
unzip -q -o "$TMP_ZIP" -d "$TMP_EXTRACT"
# Zip contains a single top-level "nicewatch-agent/" directory.
SRC_DIR="$TMP_EXTRACT/nicewatch-agent"
if [[ ! -d "$SRC_DIR" ]]; then SRC_DIR=$(find "$TMP_EXTRACT" -mindepth 1 -maxdepth 1 -type d | head -1); fi
cp -a "$SRC_DIR/." "$INSTALL_DIR/"
rm -rf "$TMP_ZIP" "$TMP_EXTRACT"

# unzip can drop the executable bit depending on how the archive was created —
# restore it explicitly so `bin/nicewatch-agent` can be exec'd.
chmod +x "$INSTALL_DIR/bin/nicewatch-agent"

# ---------- 4. Composer deps ----------
# Run composer as root (simpler + avoids "no writable HOME" / traverse issues for
# the service user during install). We chown to the service user afterwards, so
# the agent itself still runs unprivileged via systemd.
log "Installing composer dependencies"
export COMPOSER_ALLOW_SUPERUSER=1
export COMPOSER_HOME=/tmp/nicewatch-composer
( cd "$INSTALL_DIR" && composer install --no-dev --no-interaction --optimize-autoloader --quiet )

# Now hand the whole tree to the unprivileged service user (runtime owner).
chown -R "$SERVICE_USER":"$SERVICE_USER" "$INSTALL_DIR"
rm -rf "$COMPOSER_HOME"

# ---------- 5. Config ----------
# Generate the PHP file via `php -r var_export(...)` so values are properly
# escaped — never embed user-supplied strings into a heredoc that PHP will
# then parse as source code.
mkdir -p "$CONFIG_DIR"
CONFIG_FILE="$CONFIG_DIR/agent.php"

log "Writing $CONFIG_FILE"
NW_SERVER="$SERVER" NW_TOKEN="$TOKEN" NW_HOSTNAME="$HOSTNAME_ARG" \
    php -r '
        $config = [
            "server_url"       => getenv("NW_SERVER"),
            "api_token"        => getenv("NW_TOKEN"),
            "hostname"         => getenv("NW_HOSTNAME") !== "" ? getenv("NW_HOSTNAME") : null,
            "timeout_seconds"  => 10,
            "verify_tls"       => true,
            "collectors"       => ["system" => true],
        ];
        $php = "<?php\n\ndeclare(strict_types=1);\n\nreturn " . var_export($config, true) . ";\n";
        file_put_contents($argv[1], $php);
    ' "$CONFIG_FILE"

chown root:"$SERVICE_USER" "$CONFIG_FILE"
chmod 640 "$CONFIG_FILE"

# ---------- 6. systemd ----------
log "Installing systemd service + timer"
install -m 644 "$INSTALL_DIR/systemd/nicewatch-agent.service" /etc/systemd/system/
install -m 644 "$INSTALL_DIR/systemd/nicewatch-agent.timer"   /etc/systemd/system/

# Patch ExecStart in the service if INSTALL_DIR was overridden
if [[ "$INSTALL_DIR" != "/opt/nicewatch-agent" ]]; then
    sed -i "s|/opt/nicewatch-agent|$INSTALL_DIR|g" /etc/systemd/system/nicewatch-agent.service
fi

systemctl daemon-reload
systemctl enable --now nicewatch-agent.timer

# ---------- 7. Smoke test ----------
log "Verifying connectivity…"
if sudo -u "$SERVICE_USER" "$INSTALL_DIR/bin/nicewatch-agent" ping --config="$CONFIG_FILE"; then
    log "All good — the host should appear as 'online' in the NiceWatch panel within ~30 seconds."
else
    echo "Ping failed — check the token and that '$SERVER' is reachable from this host." >&2
    exit 1
fi
